'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("vbtourism.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _A10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_A10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _A4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_A4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _A5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_A5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _A6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_A6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _A7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_A7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _A8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_A8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _A9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_A9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property A1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property A2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("A2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property a5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AA2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AA2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AAA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AAA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AAAA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AAAA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AAAG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AAAG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AAAK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AAAK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BB1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BB1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BB2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BB2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property C1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property C2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CC3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CC3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property D1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property D2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("D2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DD1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DD1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DD2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DD2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DD3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DD3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FF1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FF1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FF2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FF2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FORM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FORM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property G1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property G2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property G3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("G3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GOA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GOA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GOA2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GOA2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property H1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property H2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("H2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HH1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HH1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HH2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HH2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HH3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HH3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__10_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__10_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__11_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__11_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__12_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__12_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__13_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__13_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__14_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__14_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__15_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__15_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__16_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__16_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__3_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__4_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__4_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__5_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__5_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__6_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__6_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__7_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__7_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__8_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__8_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__9_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images__9_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property K1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("K1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property K2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("K2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property K3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("K3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KERELA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KERELA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property KERELA2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KERELA2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property M1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("M1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property M2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("M2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MM1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MM2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MM3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MM3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TT2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TT2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
